name: evaluation_mil
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _tflow_select=2.1.0=gpu
  - absl-py=0.9.0=py36_0
  - astor=0.8.0=py36_0
  - blas=1.0=mkl
  - blinker=1.4=py36_0
  - brotlipy=0.7.0=py36h7b6447c_1000
  - bzip2=1.0.8=h7b6447c_0
  - c-ares=1.15.0=h7b6447c_1001
  - ca-certificates=2020.1.1=0
  - cachetools=4.1.0=py_1
  - cairo=1.14.12=h8948797_3
  - certifi=2020.4.5.2=py36_0
  - cffi=1.14.0=py36he30daa8_1
  - chardet=3.0.4=py36_1003
  - click=7.1.2=py_0
  - cryptography=2.9.2=py36h1ba5d50_0
  - cudatoolkit=10.0.130=0
  - cudnn=7.6.5=cuda10.0_0
  - cupti=10.0.130=0
  - cycler=0.10.0=py36_0
  - dbus=1.13.14=hb2f20db_0
  - expat=2.2.6=he6710b0_0
  - ffmpeg=4.0=hcdf2ecd_0
  - fontconfig=2.13.0=h9420a91_0
  - freeglut=3.0.0=hf484d3e_5
  - freetype=2.9.1=h8a8886c_1
  - glib=2.63.1=h3eb4bd4_1
  - google-auth=1.14.1=py_0
  - google-auth-oauthlib=0.4.1=py_2
  - google-pasta=0.2.0=py_0
  - graphite2=1.3.13=h23475e2_0
  - grpcio=1.27.2=py36hf8bcb03_0
  - gst-plugins-base=1.14.0=hbbd80ab_1
  - gstreamer=1.14.0=hb31296c_0
  - h5py=2.8.0=py36h989c5e5_3
  - harfbuzz=1.8.8=hffaf4a1_0
  - hdf5=1.10.2=hba1933b_1
  - icu=58.2=he6710b0_3
  - idna=2.9=py_1
  - imagesize=1.2.0=py_0
  - intel-openmp=2020.1=217
  - jasper=2.0.14=h07fcdf6_1
  - jpeg=9b=h024ee3a_2
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - kiwisolver=1.2.0=py36hfd86e86_0
  - ld_impl_linux-64=2.33.1=h53a641e_7
  - libedit=3.1.20181209=hc058e9b_0
  - libffi=3.3=he6710b0_1
  - libgcc-ng=9.1.0=hdf63c60_0
  - libgfortran-ng=7.3.0=hdf63c60_0
  - libglu=9.0.0=hf484d3e_1
  - libopencv=3.4.2=hb342d67_1
  - libopus=1.3.1=h7b6447c_0
  - libpng=1.6.37=hbc83047_0
  - libprotobuf=3.12.3=hd408876_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.1.0=h2733197_1
  - libuuid=1.0.3=h1bed415_2
  - libvpx=1.7.0=h439df22_0
  - libxcb=1.13=h1bed415_1
  - libxml2=2.9.10=he19cac6_1
  - lz4-c=1.9.2=he6710b0_0
  - markdown=3.1.1=py36_0
  - matplotlib=3.1.2=py36h4fdacc2_0
  - mkl=2020.1=217
  - mkl-service=2.3.0=py36he904b0f_0
  - mkl_fft=1.0.15=py36ha843d7b_0
  - mkl_random=1.1.1=py36h0573a6f_0
  - ncurses=6.2=he6710b0_1
  - numpy=1.18.1=py36h4f9e942_0
  - numpy-base=1.18.1=py36hde5b4d6_1
  - oauthlib=3.1.0=py_0
  - olefile=0.46=py36_0
  - opencv=3.4.2=py36h6fd60c2_1
  - openssl=1.1.1g=h7b6447c_0
  - opt_einsum=3.1.0=py_0
  - pandas=1.0.3=py36h0573a6f_0
  - patsy=0.5.1=py36_0
  - pcre=8.43=he6710b0_0
  - pillow=7.1.2=py36hb39fc2d_0
  - pip=20.1.1=py36_1
  - pixman=0.38.0=h7b6447c_0
  - protobuf=3.12.3=py36he6710b0_0
  - py-opencv=3.4.2=py36hb342d67_1
  - pyasn1=0.4.8=py_0
  - pyasn1-modules=0.2.7=py_0
  - pycparser=2.20=py_0
  - pyjwt=1.7.1=py36_0
  - pyopenssl=19.1.0=py36_0
  - pyparsing=2.4.7=py_0
  - pyqt=5.9.2=py36h05f1152_2
  - pysocks=1.7.1=py36_0
  - python=3.6.10=h7579374_2
  - python-dateutil=2.8.1=py_0
  - pytz=2020.1=py_0
  - pyyaml=5.3.1=py36h7b6447c_0
  - qt=5.9.7=h5867ecd_1
  - readline=8.0=h7b6447c_0
  - requests=2.23.0=py36_0
  - requests-oauthlib=1.3.0=py_0
  - rsa=4.0=py_0
  - scipy=1.4.1=py36h0b6359f_0
  - setuptools=47.3.0=py36_0
  - sip=4.19.8=py36hf484d3e_0
  - six=1.15.0=py_0
  - sqlite=3.31.1=h62c20be_1
  - statsmodels=0.11.1=py36h7b6447c_0
  - tensorboard-plugin-wit=1.6.0=py_0
  - tensorflow=2.0.0=gpu_py36h6b29c10_0
  - tensorflow-base=2.0.0=gpu_py36h0ec5d1f_0
  - termcolor=1.1.0=py36_1
  - tk=8.6.8=hbc83047_0
  - tornado=6.0.4=py36h7b6447c_1
  - tqdm=4.46.0=py_0
  - urllib3=1.25.9=py_0
  - werkzeug=0.16.1=py_0
  - wheel=0.34.2=py36_0
  - wrapt=1.12.1=py36h7b6447c_1
  - xz=5.2.5=h7b6447c_0
  - yaml=0.1.7=had09818_2
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.4=h0b5b093_3
  - pip:
    - astunparse==1.6.3
    - gast==0.2.2
    - opencv-python==4.2.0.34
    - scikit-learn==0.19.1
    - seaborn==0.8.1
    - tensorboard==2.0.2
    - tensorflow-estimator==2.0.1
    - tensorflow-gpu==2.0.0
prefix: /home/watze/anaconda3/envs/evaluation_mil

